### ISSUE TITLE
not working in jenkins LTS (1.509.2)

### ISSUE THREAD

**Issue by anarcat** [rtyler/vagrant-plugin#35]
in #26, we explain that this plugin doesn't work with Jenkins 1.490 or later. But that issue is closed, and I still have issues running this plugin under jenkins.

basically, any job that has some vagrant bits in it fails to load with:

```
Sep 18, 2013 3:03:25 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading job Matrix test
hudson.util.IOException2: Unable to read /var/lib/jenkins/jobs/Matrix test/config.xml
        at hudson.XmlFile.read(XmlFile.java:147)
        at hudson.model.Items.load(Items.java:220)
        at jenkins.model.Jenkins$17.run(Jenkins.java:2554)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
        at jenkins.model.Jenkins$7.runTask(Jenkins.java:888)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:662)
Caused by: com.thoughtworks.xstream.converters.ConversionException: Undefined class: Jenkins::Tasks::BuilderProxy : Undefined class: Jenkins::Tasks::BuilderProxy
---- Debugging information ----
message             : Undefined class: Jenkins::Tasks::BuilderProxy
cause-exception     : java.lang.IllegalArgumentException
cause-message       : Undefined class: Jenkins::Tasks::BuilderProxy
class               : org.jruby.runtime.builtin.IRubyObject
required-type       : org.jruby.runtime.builtin.IRubyObject
converter-type      : org.jenkinsci.jruby.JRubyXStreamConverter
path                : /matrix-project/builders/ruby-proxy-object/ruby-object
line number         : 165
class[1]            : org.jenkinsci.jruby.JRubyMapper$DynamicProxy
converter-type[1]   : org.jenkinsci.jruby.JavaProxyConverter
class[2]            : hudson.util.DescribableList
converter-type[2]   : hudson.util.DescribableList$ConverterImpl
class[3]            : hudson.matrix.MatrixProject
converter-type[3]   : hudson.util.RobustReflectionConverter
version             : null
-------------------------------
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
        at org.jenkinsci.jruby.JavaProxyConverter.unmarshal(JavaProxyConverter.java:60)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
        at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:71)
        at hudson.util.CopyOnWriteList$ConverterImpl.unmarshal(CopyOnWriteList.java:193)
        at hudson.util.DescribableList$ConverterImpl.unmarshal(DescribableList.java:263)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:333)
        at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:275)
        at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:222)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1061)
        at hudson.util.XStream2.unmarshal(XStream2.java:109)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1045)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:925)
        at hudson.XmlFile.read(XmlFile.java:143)
        ... 10 more
Caused by: java.lang.IllegalArgumentException: Undefined class: Jenkins::Tasks::BuilderProxy
        at org.jenkinsci.jruby.JRubyXStreamConverter.unmarshal(JRubyXStreamConverter.java:86)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        ... 38 more
```

This is with 0.1.4. We had similar problems with 0.1.5-SNAPSHOT which we got I don't know from where:

```
Sep 18, 2013 2:19:11 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading job D aegir 6.x-2.x deb install
hudson.util.IOException2: Unable to read /var/lib/jenkins/jobs/D aegir 6.x-2.x deb install/config.xml
        at hudson.XmlFile.read(XmlFile.java:147)
        at hudson.model.Items.load(Items.java:220)
        at jenkins.model.Jenkins$17.run(Jenkins.java:2554)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
        at jenkins.model.Jenkins$7.runTask(Jenkins.java:888)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:662)
Caused by: com.thoughtworks.xstream.converters.ConversionException: Undefined class: Java::HudsonModel::StreamBuildListener : Undefined class: Java::HudsonModel::StreamBuildListener
---- Debugging information ----
message             : Undefined class: Java::HudsonModel::StreamBuildListener
cause-exception     : java.lang.IllegalArgumentException
cause-message       : Undefined class: Java::HudsonModel::StreamBuildListener
class               : org.jruby.runtime.builtin.IRubyObject
required-type       : org.jruby.runtime.builtin.IRubyObject
converter-type      : org.jenkinsci.jruby.JRubyXStreamConverter
path                : /project/builders/ruby-proxy-object/ruby-object/object/vagrant/host/ui/listener/native
line number         : 139
class[1]            : org.jenkinsci.jruby.JRubyMapper$DynamicProxy
converter-type[1]   : org.jenkinsci.jruby.JavaProxyConverter
class[2]            : hudson.util.DescribableList
converter-type[2]   : hudson.util.DescribableList$ConverterImpl
class[3]            : hudson.model.FreeStyleProject
converter-type[3]   : hudson.util.RobustReflectionConverter
version             : null
-------------------------------
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
        at org.jenkinsci.jruby.JRubyXStreamConverter.unmarshal(JRubyXStreamConverter.java:111)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
        at org.jenkinsci.jruby.JRubyXStreamConverter.unmarshal(JRubyXStreamConverter.java:111)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
        at org.jenkinsci.jruby.JRubyXStreamConverter.unmarshal(JRubyXStreamConverter.java:111)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
        at org.jenkinsci.jruby.JRubyXStreamConverter.unmarshal(JRubyXStreamConverter.java:111)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
        at org.jenkinsci.jruby.JRubyXStreamConverter.unmarshal(JRubyXStreamConverter.java:111)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
        at org.jenkinsci.jruby.JRubyXStreamConverter.unmarshal(JRubyXStreamConverter.java:111)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
        at org.jenkinsci.jruby.JRubyXStreamConverter.unmarshal(JRubyXStreamConverter.java:111)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
        at org.jenkinsci.jruby.JavaProxyConverter.unmarshal(JavaProxyConverter.java:60)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
        at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:71)
        at hudson.util.CopyOnWriteList$ConverterImpl.unmarshal(CopyOnWriteList.java:193)
        at hudson.util.DescribableList$ConverterImpl.unmarshal(DescribableList.java:263)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:333)
        at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:275)
        at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:222)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1061)
        at hudson.util.XStream2.unmarshal(XStream2.java:109)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1045)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:925)
        at hudson.XmlFile.read(XmlFile.java:143)
        ... 10 more
Caused by: java.lang.IllegalArgumentException: Undefined class: Java::HudsonModel::StreamBuildListener
        at org.jenkinsci.jruby.JRubyXStreamConverter.unmarshal(JRubyXStreamConverter.java:86)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        ... 68 more
Sep 18, 2013 2:19:11 PM jenkins.InitReactorRunner$1 onAttained
```

this is on Debian squeeze.

**Comment by anarcat** [comment]
oh, and I noticed also that the git repo mentions 0.1.6, but that version is not available here:

https://wiki.jenkins-ci.org/display/JENKINS/Vagrant+Plugin

**Comment by exoinvitemain** [comment]
+1 how to install 0.1.6 ????
